name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Run all tests
        run: |
          cargo test --all-features --verbose
          cargo clippy --all-features -- -D warnings
          cargo fmt -- --check

      - name: Build documentation
        run: cargo doc --all-features --no-deps

      - name: Security audit
        run: |
          cargo install cargo-audit
          cargo audit

      - name: Publish to crates.io
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --all-features

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            Cargo.toml
            README.md
            LICENSE-MIT
            LICENSE-APACHE
